### PR TITLE
Add a workflow file for GitHub Actions to add support for PHP 8.0 or later and drop support for PHP 5.x

### PR DESCRIPTION
**Pull request by matsuo**
Thank you for your developing!

This PR includes a workflow file for GitHub Actions.
It also includes the following:
- Drop support for PHP 5.x
- Add support for PHP 8.0 or later

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
@till this was a good quality PR; thoughts on adding @matsuo as a contributor/maintainer?

**Comment by till** [comment]
Totally okay 👍

**Comment by matsuo** [comment]
Thank you so much!

**Comment by bkdotcom** [comment]
good to see this 'ol library getting some love

**Pull request merged**
